# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqXfuIIn_oPtr6w6CPczcoUATin2csXA
"""

import pandas as pd

# Load dataset (replace with your file if needed)
df = pd.read_csv("/content/healthcare_dataset.csv", low_memory=False)

# Check first few rows
print("\nFirst 5 rows:")
print(df.head())

# Check shape
print("\nShape of dataset:", df.shape)

# Check for missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

# -----------------------------------
# 📌 Step 3: Understand the Data
# -----------------------------------

import pandas as pd

# Load dataset (replace with your file if needed)
df = pd.read_csv("/content/healthcare_dataset.csv", low_memory=False)

# 1. Check basic info (column names, data types, non-null counts)
print("\nDataset Info:")
print(df.info())

# 2. Summary statistics for numeric columns
print("\nSummary statistics:")
print(df.describe())

# 3. Check unique values in categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns
print("\nUnique values in categorical columns:")
for col in categorical_cols:
    print(f"{col}: {df[col].nunique()} unique values")


print("\nAfter conversions:")
print(df.dtypes)

df.drop_duplicates(inplace=True)

print("\nAfter cleaning:")
print(df.info())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.histplot(df['Age'], bins=20, kde=True)
plt.title("Distribution of Patient Age")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='Gender', hue='Medical Condition', data=df)
plt.title("Medical Condition Count by Gender")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()



plt.figure(figsize=(12, 6))
sns.boxplot(x='Medical Condition', y='Billing Amount', data=df)
plt.title('Distribution of Billing Amount by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="cool")
plt.title("Correlation Heatmap of Health Metrics")
plt.show()



plt.figure(figsize=(10, 6))
sns.scatterplot(x='Age', y='Billing Amount', data=df, alpha=0.6)
plt.title('Relationship between Age and Billing Amount')
plt.xlabel('Age')
plt.ylabel('Billing Amount')
plt.grid(True)
plt.show()

import pandas as pd

# Load dataset
df = pd.read_csv("/content/healthcare_dataset.csv")

# Show first 5 rows
print(df.head())

# Show column names
print("\nColumns in dataset:")
print(df.columns)

"""# **Summary**

# Older patients (especially above 60) are at higher risk for chronic diseases like Diabetes and Heart Disease. Preventive health programs should focus on early screening for cholesterol, blood pressure, and glucose levels. Gender-specific patterns (thyroid in females, cardiac issues in males) suggest personalized healthcare strategies would be effective.**bold text** **bold text**
"""

